In [1]:
import numpy as np

$$
\begin{eqnarray}
\text{dist(x, y)} = 
\begin{bmatrix}
\sqrt{(x_{1} - y_{1})^2} & \dots & \sqrt{(x_{1} - y_{m})^2}  \\
\vdots & \ddots & \vdots \\
\sqrt{(x_{n} - y_{1})^2}& \dots & \sqrt{(x_{n} - y_{m})^2}
\end{bmatrix}
\end{eqnarray}
= \sqrt{\left(
x^2 - 2xy + y^2
\right)_{ij}}
$$

Thus with broadcasting we can use the train data $x \in \mathbb{R}^{n \times 1}$ and test data $y \in \mathbb{R}^{1 \times m}$ and calculate the distance matrix $D \in \mathbb{R}^{n \times m}$ by

$$
D = x^2 - 2xy + y^2
$$

In [49]:
x = np.array([[1,2,3],[1,2,3],[2,3,4], [5,6,7]])
x

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [50]:
y = np.array([[5,3,5],[6,3,2]])
y

array([[5, 3, 5],
       [6, 3, 2]])

In [55]:
x2 = np.square(x).sum(1).reshape(-1, 1)
x2

array([[ 14],
       [ 14],
       [ 29],
       [110]])

In [52]:
y2 = np.square(y).sum(1)
y2

array([59, 49])

In [53]:
xy = x @ y.T
xy

array([[26, 18],
       [26, 18],
       [39, 29],
       [78, 62]])

In [64]:
dists_squared = x2 - 2 * (x @ y.T) + y2
dists_squared

array([[21, 27],
       [21, 27],
       [10, 20],
       [13, 35]])

In [63]:
dists = np.sqrt(dists_squared)
dists

array([[4.58257569, 5.19615242],
       [4.58257569, 5.19615242],
       [3.16227766, 4.47213595],
       [3.60555128, 5.91607978]])